In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
pd.set_option("display.max_columns",None)

In [3]:
train_df = pd.read_excel("Datasets/interview_train.xlsx")
test_df = pd.read_excel("Datasets/interview_test.xlsx")

In [4]:
train_df.head()

Interview Id  Candidate Id  Interviewer Id          Profile  S.L.R.C  \
0  6.913030e+11  2.655774e+09             194        Developer     0.98   
1  9.214326e+11  7.123846e+08             234            Sales     0.67   
2  4.718839e+10  8.445533e+08             267  Program Manager     0.81   
3  9.943741e+11  6.511106e+09             199        Marketing     0.69   
4  3.509007e+11  3.487001e+09             221    QA Automation     0.57   

   S.L.R.I  A.T.T  L.M.I  L.M.C  S.R  L.J.T.C  L.J.T.I  N.I.C  N.I.I  S.P.I  \
0     0.02     53     88     93   32       88      106     41     66     42   
1     0.33     51     53     44   36       93      313     28     62     32   
2     0.19     60     77     75   54       52       67     26     14     57   
3     0.31     93     42    103   49      115      166     62     55     65   
4     0.43     44     44    119   66      190      394      7     32     36   

   S.P.C  L.A.C  L.A.I  Q.A     P.E.I     P.E.C  COMPLIANCE Ratio  \
0     47     13     15    6   Neutral   Neutral                98   
1     52      5     15    4   Neutral  Negative                54   
2     34      4      7    3  Positive  Positive                31   
3     75     10     10    7  Positive  Negative                24   
4     74     13      7    3  Negative  Positive                73   

   Interview duration Interviewer Intro Candidate into Opp to ask    Status  
0                  37                No            Yes        Yes  Consider  
1                  33                No             No        Yes  Consider  
2                  58                No            Yes         No  Consider  
3                  35                No            Yes         No  Consider  
4                  60               Yes            Yes         No  Consider

In [5]:
test_df.head()

Interview Id  Candidate Id  Interviewer Id          Profile  S.L.R.C  \
0  702127796635  2.381365e+09             229  Product Manager     0.52   
1  613490569071  8.428514e+08             194  Product Manager     0.87   
2  759998772623  7.681665e+09             266    QA Automation     0.60   
3  391760082113  6.627808e+09             256               HR     0.52   
4  941599210196  1.148634e+09             267               HR     0.59   

   S.L.R.I  A.T.T  L.M.I  L.M.C  S.R  L.J.T.C  L.J.T.I  N.I.C  N.I.I  S.P.I  \
0     0.48    103     53     77   30     26.0      287      8     22   69.0   
1     0.13     54     57     57   68    179.0      253     62     40   47.0   
2     0.40     50    117     93   36    137.0       31     40     52   57.0   
3     0.48    102    114     66   31    176.0      242     69     66   59.0   
4     0.41     96     73    115   23    218.0      215     69     42   74.0   

   S.P.C  L.A.C  L.A.I  Q.A     P.E.I     P.E.C  COMPLIANCE Ratio  \
0     88      5   19.0  4.0  Positive  Negative              24.0   
1     81      1    9.0  7.0  Positive   Neutral              99.0   
2     13      7   15.0  3.0  Negative  Positive              16.0   
3     10     10    4.0  6.0  Negative   Neutral              66.0   
4     20     10    4.0  6.0  Positive  Positive              47.0   

   Interview duration Interviewer Intro Candidate into Opp to ask  
0                  49               Yes            Yes        Yes  
1                  24                No            Yes        Yes  
2                  16               Yes             No        Yes  
3                  40                No             No        Yes  
4                  38                No            Yes        Yes

In [6]:
train_df.shape

(5800, 27)

In [7]:
test_df.shape

(1200, 26)

In [8]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5800 entries, 0 to 5799
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Interview Id        5800 non-null   float64
 1   Candidate Id        5800 non-null   float64
 2   Interviewer Id      5800 non-null   int64  
 3   Profile             5800 non-null   object 
 4   S.L.R.C             5800 non-null   float64
 5   S.L.R.I             5800 non-null   float64
 6   A.T.T               5800 non-null   int64  
 7   L.M.I               5800 non-null   int64  
 8   L.M.C               5800 non-null   int64  
 9   S.R                 5800 non-null   int64  
 10  L.J.T.C             5800 non-null   int64  
 11  L.J.T.I             5800 non-null   int64  
 12  N.I.C               5800 non-null   int64  
 13  N.I.I               5800 non-null   int64  
 14  S.P.I               5800 non-null   int64  
 15  S.P.C               5800 non-null   int64  
 16  L.A.C 

In [9]:
train_df['Candidate Id'].nunique()

5800

In [10]:
train_df['Interview Id'].nunique()

5800

In [11]:
train_df.describe(include='all')

Interview Id  Candidate Id  Interviewer Id    Profile      S.L.R.C  \
count   5.800000e+03  5.800000e+03     5800.000000       5800  5800.000000   
unique           NaN           NaN             NaN         10          NaN   
top              NaN           NaN             NaN  Developer          NaN   
freq             NaN           NaN             NaN        618          NaN   
mean    4.947029e+11  5.009458e+09      229.553448        NaN     0.748321   
std     2.890097e+11  2.873886e+09       22.884836        NaN     0.144272   
min     3.693968e+08  1.467066e+05      190.000000        NaN     0.500000   
25%     2.423758e+11  2.513537e+09      210.000000        NaN     0.620000   
50%     4.900364e+11  5.009811e+09      229.000000        NaN     0.750000   
75%     7.456835e+11  7.468382e+09      250.000000        NaN     0.870000   
max     9.999089e+11  9.999362e+09      268.000000        NaN     0.990000   

            S.L.R.I        A.T.T        L.M.I        L.M.C          S.R  \
count   5800.000000  5800.000000  5800.000000  5800.000000  5800.000000   
unique          NaN          NaN          NaN          NaN          NaN   
top             NaN          NaN          NaN          NaN          NaN   
freq            NaN          NaN          NaN          NaN          NaN   
mean       0.251679    69.927414    80.445172    80.084310    45.077414   
std        0.144272    29.464030    23.450059    23.540515    14.729066   
min        0.010000    20.000000    40.000000    40.000000    20.000000   
25%        0.130000    44.000000    60.000000    59.000000    32.000000   
50%        0.250000    70.000000    81.000000    81.000000    45.000000   
75%        0.380000    96.000000   101.000000   101.000000    58.000000   
max        0.500000   120.000000   120.000000   120.000000    70.000000   

            L.J.T.C      L.J.T.I        N.I.C        N.I.I        S.P.I  \
count   5800.000000  5800.000000  5800.000000  5800.000000  5800.000000   
unique          NaN          NaN          NaN          NaN          NaN   
top             NaN          NaN          NaN          NaN          NaN   
freq            NaN          NaN          NaN          NaN          NaN   
mean     150.231207   301.063103    37.709828    37.378448    55.175862   
std       87.265858   172.861851    19.042870    19.138247    20.373655   
min        0.000000     0.000000     5.000000     5.000000    20.000000   
25%       74.000000   153.000000    21.000000    21.000000    38.000000   
50%      150.000000   300.000000    38.000000    37.000000    55.000000   
75%      226.000000   451.000000    54.000000    54.000000    73.000000   
max      300.000000   600.000000    70.000000    70.000000    90.000000   

              S.P.C        L.A.C        L.A.I          Q.A     P.E.I    P.E.C  \
count   5800.000000  5800.000000  5800.000000  5800.000000      5799     5797   
unique          NaN          NaN          NaN          NaN         3        3   
top             NaN          NaN          NaN          NaN  Negative  Neutral   
freq            NaN          NaN          NaN          NaN      2004     1971   
mean      47.250690     8.019655    10.503621     4.507586       NaN      NaN   
std       24.891818     4.311379     5.724640     1.690976       NaN      NaN   
min        5.000000     1.000000     1.000000     2.000000       NaN      NaN   
25%       26.000000     4.000000     6.000000     3.000000       NaN      NaN   
50%       46.000000     8.000000    10.000000     5.000000       NaN      NaN   
75%       69.000000    12.000000    15.000000     6.000000       NaN      NaN   
max       90.000000    15.000000    20.000000     7.000000       NaN      NaN   

        COMPLIANCE Ratio  Interview duration Interviewer Intro Candidate into  \
count        5800.000000         5800.000000              5799           5800   
unique               NaN                 NaN                 2              2   
top                  NaN                 NaN         

In [12]:
train_df['Interviewer Id'].nunique()

79

In [13]:
train_df['Status'].nunique()

3

In [14]:
train_df['Status'].unique()

array(['Consider', 'May Consider', 'Not Consider', nan], dtype=object)

In [4]:
train_df.drop(['Interviewer Id','Candidate Id'],axis=1,inplace=True)
test_df.drop(['Interviewer Id','Candidate Id'],axis=1,inplace=True)

In [5]:
train_df.set_index('Interview Id',inplace=True)
test_df.set_index('Interview Id',inplace=True)

In [17]:
#train_df.set_index?

In [18]:
print(train_df.shape)
print(test_df.shape)

(5800, 24)
(1200, 23)


In [19]:
train_df.head()

Profile  S.L.R.C  S.L.R.I  A.T.T  L.M.I  L.M.C  S.R  \
Interview Id                                                                
6.913030e+11        Developer     0.98     0.02     53     88     93   32   
9.214326e+11            Sales     0.67     0.33     51     53     44   36   
4.718839e+10  Program Manager     0.81     0.19     60     77     75   54   
9.943741e+11        Marketing     0.69     0.31     93     42    103   49   
3.509007e+11    QA Automation     0.57     0.43     44     44    119   66   

              L.J.T.C  L.J.T.I  N.I.C  N.I.I  S.P.I  S.P.C  L.A.C  L.A.I  Q.A  \
Interview Id                                                                    
6.913030e+11       88      106     41     66     42     47     13     15    6   
9.214326e+11       93      313     28     62     32     52      5     15    4   
4.718839e+10       52       67     26     14     57     34      4      7    3   
9.943741e+11      115      166     62     55     65     75     10     10    7   
3.509007e+11      190      394      7     32     36     74     13      7    3   

                 P.E.I     P.E.C  COMPLIANCE Ratio  Interview duration  \
Interview Id                                                             
6.913030e+11   Neutral   Neutral                98                  37   
9.214326e+11   Neutral  Negative                54                  33   
4.718839e+10  Positive  Positive                31                  58   
9.943741e+11  Positive  Negative                24                  35   
3.509007e+11  Negative  Positive                73                  60   

             Interviewer Intro Candidate into Opp to ask    Status  
Interview Id                                                        
6.913030e+11                No            Yes        Yes  Consider  
9.214326e+11                No             No        Yes  Consider  
4.718839e+10                No            Yes         No  Consider  
9.943741e+11                No            Yes         No  Consider  
3.509007e+11               Yes            Yes         No  Consider

In [20]:
test_df.head()

Profile  S.L.R.C  S.L.R.I  A.T.T  L.M.I  L.M.C  S.R  \
Interview Id                                                                
702127796635  Product Manager     0.52     0.48    103     53     77   30   
613490569071  Product Manager     0.87     0.13     54     57     57   68   
759998772623    QA Automation     0.60     0.40     50    117     93   36   
391760082113               HR     0.52     0.48    102    114     66   31   
941599210196               HR     0.59     0.41     96     73    115   23   

              L.J.T.C  L.J.T.I  N.I.C  N.I.I  S.P.I  S.P.C  L.A.C  L.A.I  Q.A  \
Interview Id                                                                    
702127796635     26.0      287      8     22   69.0     88      5   19.0  4.0   
613490569071    179.0      253     62     40   47.0     81      1    9.0  7.0   
759998772623    137.0       31     40     52   57.0     13      7   15.0  3.0   
391760082113    176.0      242     69     66   59.0     10     10    4.0  6.0   
941599210196    218.0      215     69     42   74.0     20     10    4.0  6.0   

                 P.E.I     P.E.C  COMPLIANCE Ratio  Interview duration  \
Interview Id                                                             
702127796635  Positive  Negative              24.0                  49   
613490569071  Positive   Neutral              99.0                  24   
759998772623  Negative  Positive              16.0                  16   
391760082113  Negative   Neutral              66.0                  40   
941599210196  Positive  Positive              47.0                  38   

             Interviewer Intro Candidate into Opp to ask  
Interview Id                                              
702127796635               Yes            Yes        Yes  
613490569071                No            Yes        Yes  
759998772623               Yes             No        Yes  
391760082113                No             No        Yes  
941599210196                No            Yes        Yes

In [21]:
train_df.isnull().sum()

Profile               0
S.L.R.C               0
S.L.R.I               0
A.T.T                 0
L.M.I                 0
L.M.C                 0
S.R                   0
L.J.T.C               0
L.J.T.I               0
N.I.C                 0
N.I.I                 0
S.P.I                 0
S.P.C                 0
L.A.C                 0
L.A.I                 0
Q.A                   0
P.E.I                 1
P.E.C                 3
COMPLIANCE Ratio      0
Interview duration    0
Interviewer Intro     1
Candidate into        0
Opp to ask            1
Status                4
dtype: int64

In [6]:
train_df.dropna(subset=['P.E.I','P.E.C','Interviewer Intro','Opp to ask','Status'],axis=0,inplace=True)

In [23]:
train_df.isnull().sum()

Profile               0
S.L.R.C               0
S.L.R.I               0
A.T.T                 0
L.M.I                 0
L.M.C                 0
S.R                   0
L.J.T.C               0
L.J.T.I               0
N.I.C                 0
N.I.I                 0
S.P.I                 0
S.P.C                 0
L.A.C                 0
L.A.I                 0
Q.A                   0
P.E.I                 0
P.E.C                 0
COMPLIANCE Ratio      0
Interview duration    0
Interviewer Intro     0
Candidate into        0
Opp to ask            0
Status                0
dtype: int64

In [24]:
test_df.isnull().sum()

Profile               0
S.L.R.C               0
S.L.R.I               1
A.T.T                 0
L.M.I                 0
L.M.C                 0
S.R                   0
L.J.T.C               1
L.J.T.I               0
N.I.C                 0
N.I.I                 0
S.P.I                 2
S.P.C                 0
L.A.C                 0
L.A.I                 1
Q.A                   1
P.E.I                 2
P.E.C                 2
COMPLIANCE Ratio      1
Interview duration    0
Interviewer Intro     2
Candidate into        0
Opp to ask            0
dtype: int64

In [7]:
test_df.dropna(subset=['P.E.I','P.E.C','Interviewer Intro','COMPLIANCE Ratio','Q.A','L.A.I','S.P.I','L.J.T.C','S.L.R.I'],axis=0,inplace=True)

In [26]:
test_df.isnull().sum()

Profile               0
S.L.R.C               0
S.L.R.I               0
A.T.T                 0
L.M.I                 0
L.M.C                 0
S.R                   0
L.J.T.C               0
L.J.T.I               0
N.I.C                 0
N.I.I                 0
S.P.I                 0
S.P.C                 0
L.A.C                 0
L.A.I                 0
Q.A                   0
P.E.I                 0
P.E.C                 0
COMPLIANCE Ratio      0
Interview duration    0
Interviewer Intro     0
Candidate into        0
Opp to ask            0
dtype: int64

In [27]:
train_df.duplicated().sum()

0

In [28]:
test_df.duplicated().sum()

0

In [29]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5790 entries, 691302971928.0 to 863040675358.0
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Profile             5790 non-null   object 
 1   S.L.R.C             5790 non-null   float64
 2   S.L.R.I             5790 non-null   float64
 3   A.T.T               5790 non-null   int64  
 4   L.M.I               5790 non-null   int64  
 5   L.M.C               5790 non-null   int64  
 6   S.R                 5790 non-null   int64  
 7   L.J.T.C             5790 non-null   int64  
 8   L.J.T.I             5790 non-null   int64  
 9   N.I.C               5790 non-null   int64  
 10  N.I.I               5790 non-null   int64  
 11  S.P.I               5790 non-null   int64  
 12  S.P.C               5790 non-null   int64  
 13  L.A.C               5790 non-null   int64  
 14  L.A.I               5790 non-null   int64  
 15  Q.A                 5790 non-null   i

In [30]:
train_df.describe(include='all')

Profile      S.L.R.C      S.L.R.I        A.T.T        L.M.I  \
count        5790  5790.000000  5790.000000  5790.000000  5790.000000   
unique         10          NaN          NaN          NaN          NaN   
top     Developer          NaN          NaN          NaN          NaN   
freq          618          NaN          NaN          NaN          NaN   
mean          NaN     0.748268     0.251732    69.946805    80.451641   
std           NaN     0.144249     0.144249    29.465837    23.451585   
min           NaN     0.500000     0.010000    20.000000    40.000000   
25%           NaN     0.620000     0.130000    44.000000    60.000000   
50%           NaN     0.750000     0.250000    70.000000    81.000000   
75%           NaN     0.870000     0.380000    96.000000   101.000000   
max           NaN     0.990000     0.500000   120.000000   120.000000   

              L.M.C          S.R      L.J.T.C      L.J.T.I        N.I.C  \
count   5790.000000  5790.000000  5790.000000  5790.000000  5790.000000   
unique          NaN          NaN          NaN          NaN          NaN   
top             NaN          NaN          NaN          NaN          NaN   
freq            NaN          NaN          NaN          NaN          NaN   
mean      80.082383    45.079275   150.267876   300.969948    37.710017   
std       23.544798    14.735396    87.272489   172.904739    19.048039   
min       40.000000    20.000000     0.000000     0.000000     5.000000   
25%       59.250000    32.000000    74.000000   153.000000    21.000000   
50%       81.000000    45.000000   150.000000   300.000000    38.000000   
75%      101.000000    58.000000   226.000000   451.000000    54.000000   
max      120.000000    70.000000   300.000000   600.000000    70.000000   

              N.I.I        S.P.I        S.P.C        L.A.C        L.A.I  \
count   5790.000000  5790.000000  5790.000000  5790.000000  5790.000000   
unique          NaN          NaN          NaN          NaN          NaN   
top             NaN          NaN          NaN          NaN          NaN   
freq            NaN          NaN          NaN          NaN          NaN   
mean      37.373402    55.178584    47.265803     8.018653    10.501900   
std       19.135869    20.379943    24.898557     4.309899     5.725805   
min        5.000000    20.000000     5.000000     1.000000     1.000000   
25%       21.000000    38.000000    26.000000     4.000000     6.000000   
50%       37.000000    55.000000    46.000000     8.000000    10.000000   
75%       54.000000    73.000000    69.000000    12.000000    15.000000   
max       70.000000    90.000000    90.000000    15.000000    20.000000   

                Q.A     P.E.I    P.E.C  COMPLIANCE Ratio  Interview duration  \
count   5790.000000      5790     5790       5790.000000         5790.000000   
unique          NaN         3        3               NaN                 NaN   
top             NaN  Negative  Neutral               NaN                 NaN   
freq            NaN      1999     1968               NaN                 NaN   
mean       4.507081       NaN      NaN         50.337651           37.307427   
std        1.691290       NaN      NaN         28.699222           13.298042   
min        2.000000       NaN      NaN          0.000000           15.000000   
25%        3.000000       NaN      NaN         25.000000           26.000000   
50%        5.000000       NaN      NaN         51.000000           37.000000   
75%        6.000000       NaN      NaN         75.000000           49.000000   
max        7.000000       NaN      NaN        100.000000           60.000000   

       Interviewer Intro Candidate into Opp to ask    Status  
count               5790           5790       5790      5790  
unique                 2              2          2         3  
top                   No             No        Yes  Consider  
freq                2907           2932       2953      2309  
mean                 NaN            NaN        NaN     

In [31]:
test_df.describe(include='all')

Profile      S.L.R.C      S.L.R.I        A.T.T        L.M.I  \
count              1187  1187.000000  1187.000000  1187.000000  1187.000000   
unique               10          NaN          NaN          NaN          NaN   
top     Account Manager          NaN          NaN          NaN          NaN   
freq                132          NaN          NaN          NaN          NaN   
mean                NaN     0.737826     0.262174    70.153328    79.538332   
std                 NaN     0.144447     0.144447    29.117545    23.098130   
min                 NaN     0.500000     0.010000    20.000000    40.000000   
25%                 NaN     0.610000     0.140000    44.500000    59.000000   
50%                 NaN     0.740000     0.260000    71.000000    79.000000   
75%                 NaN     0.860000     0.390000    96.000000    99.500000   
max                 NaN     0.990000     0.500000   120.000000   120.000000   

              L.M.C          S.R      L.J.T.C      L.J.T.I        N.I.C  \
count   1187.000000  1187.000000  1187.000000  1187.000000  1187.000000   
unique          NaN          NaN          NaN          NaN          NaN   
top             NaN          NaN          NaN          NaN          NaN   
freq            NaN          NaN          NaN          NaN          NaN   
mean      81.410278    45.055602   151.598147   305.304971    37.466723   
std       23.103207    14.591351    86.869275   175.610301    18.955469   
min       40.000000    20.000000     0.000000     0.000000     5.000000   
25%       62.000000    32.000000    79.000000   151.500000    21.000000   
50%       81.000000    45.000000   151.000000   306.000000    37.000000   
75%      102.000000    57.500000   228.000000   457.500000    54.000000   
max      120.000000    70.000000   300.000000   599.000000    70.000000   

              N.I.I        S.P.I        S.P.C        L.A.C        L.A.I  \
count   1187.000000  1187.000000  1187.000000  1187.000000  1187.000000   
unique          NaN          NaN          NaN          NaN          NaN   
top             NaN          NaN          NaN          NaN          NaN   
freq            NaN          NaN          NaN          NaN          NaN   
mean      37.668071    54.754844    47.972199     7.823926    10.716933   
std       19.190121    20.659442    24.345152     4.406247     5.730079   
min        5.000000    20.000000     5.000000     1.000000     1.000000   
25%       20.000000    37.000000    28.000000     4.000000     6.000000   
50%       38.000000    55.000000    48.000000     8.000000    11.000000   
75%       54.000000    73.000000    69.000000    12.000000    16.000000   
max       70.000000    90.000000    90.000000    15.000000    20.000000   

                Q.A     P.E.I     P.E.C  COMPLIANCE Ratio  Interview duration  \
count   1187.000000      1187      1187       1187.000000         1187.000000   
unique          NaN         3         3               NaN                 NaN   
top             NaN  Negative  Positive               NaN                 NaN   
freq            NaN       405       409               NaN                 NaN   
mean       4.366470       NaN       NaN         50.144061           37.743892   
std        1.687566       NaN       NaN         29.360072           13.382495   
min        2.000000       NaN       NaN          0.000000           15.000000   
25%        3.000000       NaN       NaN         23.000000           26.000000   
50%        4.000000       NaN       NaN         50.000000           38.000000   
75%        6.000000       NaN       NaN         76.000000           50.000000   
max        7.000000       NaN       NaN        100.000000           60.000000   

       Interviewer Intro Candidate into Opp to ask  
count               1187           1187       1187  
unique                 2              2          2  
top                   No            Yes         No  
freq                 594            606        595  
mean                 NaN   

In [32]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1187 entries, 702127796635 to 480519602140
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Profile             1187 non-null   object 
 1   S.L.R.C             1187 non-null   float64
 2   S.L.R.I             1187 non-null   float64
 3   A.T.T               1187 non-null   int64  
 4   L.M.I               1187 non-null   int64  
 5   L.M.C               1187 non-null   int64  
 6   S.R                 1187 non-null   int64  
 7   L.J.T.C             1187 non-null   float64
 8   L.J.T.I             1187 non-null   int64  
 9   N.I.C               1187 non-null   int64  
 10  N.I.I               1187 non-null   int64  
 11  S.P.I               1187 non-null   float64
 12  S.P.C               1187 non-null   int64  
 13  L.A.C               1187 non-null   int64  
 14  L.A.I               1187 non-null   float64
 15  Q.A                 1187 non-null   float

In [33]:
for i in train_df.columns:
    print({i:train_df[i].unique()})

{'Profile': array(['Developer', 'Sales', 'Program Manager', 'Marketing',
       'QA Automation', 'Account Manager', 'Data Scientist',
       'Product Manager', 'QA Manual', 'HR'], dtype=object)}
{'S.L.R.C': array([0.98, 0.67, 0.81, 0.69, 0.57, 0.65, 0.52, 0.91, 0.72, 0.82, 0.66,
       0.51, 0.54, 0.55, 0.5 , 0.79, 0.83, 0.73, 0.63, 0.62, 0.88, 0.8 ,
       0.99, 0.68, 0.85, 0.84, 0.7 , 0.93, 0.87, 0.94, 0.71, 0.58, 0.77,
       0.96, 0.76, 0.61, 0.53, 0.59, 0.75, 0.92, 0.64, 0.97, 0.95, 0.56,
       0.89, 0.86, 0.6 , 0.78, 0.74, 0.9 ])}
{'S.L.R.I': array([0.02, 0.33, 0.19, 0.31, 0.43, 0.35, 0.48, 0.09, 0.28, 0.18, 0.34,
       0.49, 0.46, 0.45, 0.5 , 0.21, 0.17, 0.27, 0.37, 0.38, 0.12, 0.2 ,
       0.01, 0.32, 0.15, 0.16, 0.3 , 0.07, 0.13, 0.06, 0.29, 0.42, 0.23,
       0.04, 0.24, 0.39, 0.47, 0.41, 0.25, 0.08, 0.36, 0.03, 0.05, 0.44,
       0.11, 0.14, 0.4 , 0.22, 0.26, 0.1 ])}
{'A.T.T': array([ 53,  51,  60,  93,  44,  75,  49,  66,  36,  27,  24, 116,  50,
        85,  78,  62,  95

In [34]:
for i in test_df.columns:
    print({i:test_df[i].unique()})

{'Profile': array(['Product Manager', 'QA Automation', 'HR', 'Developer',
       'Account Manager', 'Program Manager', 'Sales', 'Data Scientist',
       'QA Manual', 'Marketing'], dtype=object)}
{'S.L.R.C': array([0.52, 0.87, 0.6 , 0.59, 0.88, 0.81, 0.99, 0.67, 0.58, 0.78, 0.68,
       0.85, 0.9 , 0.84, 0.93, 0.77, 0.69, 0.57, 0.98, 0.54, 0.53, 0.75,
       0.79, 0.74, 0.86, 0.71, 0.82, 0.55, 0.65, 0.56, 0.95, 0.61, 0.62,
       0.72, 0.66, 0.7 , 0.64, 0.96, 0.51, 0.73, 0.76, 0.97, 0.8 , 0.92,
       0.5 , 0.63, 0.94, 0.83, 0.91, 0.89])}
{'S.L.R.I': array([0.48, 0.13, 0.4 , 0.41, 0.12, 0.19, 0.01, 0.33, 0.42, 0.22, 0.32,
       0.15, 0.1 , 0.16, 0.07, 0.23, 0.31, 0.43, 0.02, 0.46, 0.47, 0.25,
       0.21, 0.26, 0.14, 0.29, 0.18, 0.45, 0.35, 0.44, 0.05, 0.39, 0.38,
       0.28, 0.34, 0.3 , 0.36, 0.04, 0.49, 0.27, 0.24, 0.03, 0.2 , 0.08,
       0.5 , 0.37, 0.06, 0.17, 0.09, 0.11])}
{'A.T.T': array([103,  54,  50, 102,  96,  23,  52,  67,  35,  49, 100,  29,  77,
        56,  85,  95, 110

In [8]:
#create X and Y
X=train_df.iloc[:,0:-1]
Y=train_df.iloc[:,-1]

In [36]:
print(X.shape)
print(Y.shape)

(5790, 23)
(5790,)


In [9]:
colname=[]
for x in train_df.columns[:-1]:
    if train_df[x].dtype=='object':
        colname.append(x)
colname

['Profile',
 'P.E.I',
 'P.E.C',
 'Interviewer Intro',
 'Candidate into',
 'Opp to ask']

In [38]:
X.head()

Profile  S.L.R.C  S.L.R.I  A.T.T  L.M.I  L.M.C  S.R  \
Interview Id                                                                
6.913030e+11        Developer     0.98     0.02     53     88     93   32   
9.214326e+11            Sales     0.67     0.33     51     53     44   36   
4.718839e+10  Program Manager     0.81     0.19     60     77     75   54   
9.943741e+11        Marketing     0.69     0.31     93     42    103   49   
3.509007e+11    QA Automation     0.57     0.43     44     44    119   66   

              L.J.T.C  L.J.T.I  N.I.C  N.I.I  S.P.I  S.P.C  L.A.C  L.A.I  Q.A  \
Interview Id                                                                    
6.913030e+11       88      106     41     66     42     47     13     15    6   
9.214326e+11       93      313     28     62     32     52      5     15    4   
4.718839e+10       52       67     26     14     57     34      4      7    3   
9.943741e+11      115      166     62     55     65     75     10     10    7   
3.509007e+11      190      394      7     32     36     74     13      7    3   

                 P.E.I     P.E.C  COMPLIANCE Ratio  Interview duration  \
Interview Id                                                             
6.913030e+11   Neutral   Neutral                98                  37   
9.214326e+11   Neutral  Negative                54                  33   
4.718839e+10  Positive  Positive                31                  58   
9.943741e+11  Positive  Negative                24                  35   
3.509007e+11  Negative  Positive                73                  60   

             Interviewer Intro Candidate into Opp to ask  
Interview Id                                              
6.913030e+11                No            Yes        Yes  
9.214326e+11                No             No        Yes  
4.718839e+10                No            Yes         No  
9.943741e+11                No            Yes         No  
3.509007e+11               Yes            Yes         No

In [10]:
# For preprocessing the data
from sklearn.preprocessing import LabelEncoder
 
le=LabelEncoder()
 
for x in colname:
    X[x]=le.fit_transform(X[x]) #mandatory
    

    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_))) #optional check labels
    print('Feature', x)
    print('mapping', le_name_mapping)

Feature Profile
mapping {'Account Manager': 0, 'Data Scientist': 1, 'Developer': 2, 'HR': 3, 'Marketing': 4, 'Product Manager': 5, 'Program Manager': 6, 'QA Automation': 7, 'QA Manual': 8, 'Sales': 9}
Feature P.E.I
mapping {'Negative': 0, 'Neutral': 1, 'Positive': 2}
Feature P.E.C
mapping {'Negative': 0, 'Neutral': 1, 'Positive': 2}
Feature Interviewer Intro
mapping {'No': 0, 'Yes': 1}
Feature Candidate into
mapping {'No': 0, 'Yes': 1}
Feature Opp to ask
mapping {'No': 0, 'Yes': 1}


In [40]:
X.head()

Profile  S.L.R.C  S.L.R.I  A.T.T  L.M.I  L.M.C  S.R  L.J.T.C  \
Interview Id                                                                 
6.913030e+11        2     0.98     0.02     53     88     93   32       88   
9.214326e+11        9     0.67     0.33     51     53     44   36       93   
4.718839e+10        6     0.81     0.19     60     77     75   54       52   
9.943741e+11        4     0.69     0.31     93     42    103   49      115   
3.509007e+11        7     0.57     0.43     44     44    119   66      190   

              L.J.T.I  N.I.C  N.I.I  S.P.I  S.P.C  L.A.C  L.A.I  Q.A  P.E.I  \
Interview Id                                                                  
6.913030e+11      106     41     66     42     47     13     15    6      1   
9.214326e+11      313     28     62     32     52      5     15    4      1   
4.718839e+10       67     26     14     57     34      4      7    3      2   
9.943741e+11      166     62     55     65     75     10     10    7      2   
3.509007e+11      394      7     32     36     74     13      7    3      0   

              P.E.C  COMPLIANCE Ratio  Interview duration  Interviewer Intro  \
Interview Id                                                                   
6.913030e+11      1                98                  37                  0   
9.214326e+11      0                54                  33                  0   
4.718839e+10      2                31                  58                  0   
9.943741e+11      0                24                  35                  0   
3.509007e+11      2                73                  60                  1   

              Candidate into  Opp to ask  
Interview Id                              
6.913030e+11               1           1  
9.214326e+11               0           1  
4.718839e+10               1           0  
9.943741e+11               1           0  
3.509007e+11               1           0

In [11]:
colname1=[]
for x in test_df.columns:
    if test_df[x].dtype=='object':
        colname1.append(x)
colname1

['Profile',
 'P.E.I',
 'P.E.C',
 'Interviewer Intro',
 'Candidate into',
 'Opp to ask']

In [12]:
# For preprocessing the data
from sklearn.preprocessing import LabelEncoder
 
le1=LabelEncoder()
 
for x in colname1:
    test_df[x]=le1.fit_transform(test_df[x]) #mandatory
    

    le1_name_mapping = dict(zip(le1.classes_, le1.transform(le1.classes_))) #optional check labels
    print('Feature', x)
    print('mapping', le1_name_mapping)

Feature Profile
mapping {'Account Manager': 0, 'Data Scientist': 1, 'Developer': 2, 'HR': 3, 'Marketing': 4, 'Product Manager': 5, 'Program Manager': 6, 'QA Automation': 7, 'QA Manual': 8, 'Sales': 9}
Feature P.E.I
mapping {'Negative': 0, 'Neutral': 1, 'Positive': 2}
Feature P.E.C
mapping {'Negative': 0, 'Neutral': 1, 'Positive': 2}
Feature Interviewer Intro
mapping {'No': 0, 'Yes': 1}
Feature Candidate into
mapping {'No': 0, 'Yes': 1}
Feature Opp to ask
mapping {'No': 0, 'Yes': 1}


In [13]:
from sklearn.preprocessing import StandardScaler
 
scaler=StandardScaler()
scaler.fit(X)             
X=scaler.transform(X)
print(X)

[[-0.86164066  1.60661481 -1.60661481 ... -0.99586348  1.01286338
   0.98016219]
 [ 1.56351878 -0.54263498  0.54263498 ... -0.99586348 -0.98729998
   0.98016219]
 [ 0.52416473  0.42799396 -0.42799396 ... -0.99586348  1.01286338
  -1.02023932]
 ...
 [ 0.17771339 -0.75062689  0.75062689 ... -0.99586348  1.01286338
  -1.02023932]
 [ 1.56351878  1.32929225 -1.32929225 ...  1.0041537   1.01286338
   0.98016219]
 [-0.86164066  0.56665523 -0.56665523 ... -0.99586348 -0.98729998
  -1.02023932]]


In [44]:
Y.value_counts()

Status
Consider        2309
May Consider    1886
Not Consider    1595
Name: count, dtype: int64

In [45]:
X.shape

(5790, 23)

In [14]:
test_df_scale=scaler.transform(test_df)
print(test_df_scale)

[[ 0.17771339 -1.58259455  1.58259455 ...  1.0041537   1.01286338
   0.98016219]
 [ 0.17771339  0.84397779 -0.84397779 ... -0.99586348  1.01286338
   0.98016219]
 [ 0.87061608 -1.02794945  1.02794945 ...  1.0041537  -0.98729998
   0.98016219]
 ...
 [-0.51518931 -0.12665115  0.12665115 ...  1.0041537   1.01286338
  -1.02023932]
 [-0.86164066  1.39862289 -1.39862289 ... -0.99586348 -0.98729998
  -1.02023932]
 [ 1.56351878  1.53728417 -1.53728417 ... -0.99586348 -0.98729998
   0.98016219]]


In [47]:
test_df_scale.shape

(1187, 23)

In [15]:
#train set and validation set split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [49]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(4632, 23)
(4632,)
(1158, 23)
(1158,)


In [50]:
from sklearn.tree import DecisionTreeClassifier
#create a model object
model_DecisionTree = DecisionTreeClassifier(random_state=10,criterion='gini')
# train the model object
model_DecisionTree.fit(x_train,y_train) #trainig phase is building the DTree fit Tree

y_pred=model_DecisionTree.predict(x_test)
print(y_pred)

['Consider' 'Not Consider' 'Not Consider' ... 'Consider' 'Consider'
 'May Consider']


In [51]:
model_DecisionTree.score(x_train, y_train)

1.0

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(y_test,y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(y_test,y_pred))
 
acc=accuracy_score(y_test, y_pred)
print("Accuracy of the model: ",acc)

[[414  38   0]
 [ 34 307  45]
 [  0  39 281]]
Classification report: 
              precision    recall  f1-score   support

    Consider       0.92      0.92      0.92       452
May Consider       0.80      0.80      0.80       386
Not Consider       0.86      0.88      0.87       320

    accuracy                           0.87      1158
   macro avg       0.86      0.86      0.86      1158
weighted avg       0.87      0.87      0.87      1158

Accuracy of the model:  0.8652849740932642


In [53]:
sample=pd.DataFrame()
 
sample["Column"]=train_df.columns[0:-1]
sample["Imp value"]=model_DecisionTree.feature_importances_
 
sample.sort_values("Imp value",ascending=False)

Column  Imp value
7              L.J.T.C   0.584269
12               S.P.C   0.117411
9                N.I.C   0.082989
5                L.M.C   0.077903
19  Interview duration   0.052002
3                A.T.T   0.010031
13               L.A.C   0.008885
8              L.J.T.I   0.008069
11               S.P.I   0.007783
4                L.M.I   0.007597
18    COMPLIANCE Ratio   0.007379
1              S.L.R.C   0.006250
14               L.A.I   0.005847
10               N.I.I   0.005469
6                  S.R   0.005208
2              S.L.R.I   0.004647
15                 Q.A   0.002248
16               P.E.I   0.002074
0              Profile   0.001425
17               P.E.C   0.001093
21      Candidate into   0.000929
20   Interviewer Intro   0.000492
22          Opp to ask   0.000000

In [54]:
#last 3 cols less imp acc to DTree
# opp to ask 0% imp

In [55]:
# predicting using the Decision_Tree_classifier
from sklearn.tree import DecisionTreeClassifier

model_DT = DecisionTreeClassifier(random_state=10,
                                  criterion='gini',
                                 splitter="best",
                                 min_samples_leaf=3,
                                 min_samples_split=5,
                                 max_depth=10,
                                  max_leaf_nodes=100,
                                  #max_features=0.6
                                 )
# min_samples_leaf , min_samples_split, max_depth, max_features, max_leaf_nodes

# fit the model on the data and predict the values
model_DT.fit(x_train,y_train)
Y_pred1=model_DT.predict(x_test)
# print(list(zip(Y_test,Y_pred)))
#print(list(zip(Y_test,Y_pred)))

In [56]:
model_DT.score(x_train, y_train)

0.9488341968911918

In [57]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(y_test,Y_pred1)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(y_test,Y_pred1))
 
acc=accuracy_score(y_test, Y_pred1)
print("Accuracy of the model: ",acc)

[[409  43   0]
 [ 28 321  37]
 [  0  34 286]]
Classification report: 
              precision    recall  f1-score   support

    Consider       0.94      0.90      0.92       452
May Consider       0.81      0.83      0.82       386
Not Consider       0.89      0.89      0.89       320

    accuracy                           0.88      1158
   macro avg       0.88      0.88      0.88      1158
weighted avg       0.88      0.88      0.88      1158

Accuracy of the model:  0.8773747841105354


In [58]:
#Prunned DTree is better 87

In [59]:
#try grid search cv

In [60]:
from sklearn.ensemble import RandomForestClassifier
#create a model object
model_RandomForest = RandomForestClassifier(random_state=10,n_estimators=100,bootstrap=True,n_jobs=-1)
# train the model object
model_RandomForest.fit(x_train,y_train) #trainig phase is building the DTree Trees 100

y_pred_forest=model_RandomForest.predict(x_test)
#print(y_pred_forest)

In [61]:
model_RandomForest.score(x_train, y_train)

1.0

In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(y_test,y_pred_forest)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(y_test,y_pred_forest))
 
acc=accuracy_score(y_test, y_pred_forest)
print("Accuracy of the model: ",acc)

[[415  37   0]
 [ 39 315  32]
 [  0  31 289]]
Classification report: 
              precision    recall  f1-score   support

    Consider       0.91      0.92      0.92       452
May Consider       0.82      0.82      0.82       386
Not Consider       0.90      0.90      0.90       320

    accuracy                           0.88      1158
   macro avg       0.88      0.88      0.88      1158
weighted avg       0.88      0.88      0.88      1158

Accuracy of the model:  0.8799654576856649


In [63]:
from sklearn.tree import DecisionTreeClassifier
 
model_DT1= DecisionTreeClassifier(random_state=10) #fixed parameters should be passsed here
 
#parameters for trial and error should be passed here
parameter_space = {
          #np.arange(100, 1001,50),
    'max_depth':[10,15,8, 12],
    'min_samples_leaf':[1,3,4,5,6,7]
    }
from sklearn.model_selection import GridSearchCV #RandomizedSearchCV
clf = GridSearchCV(model_DT1, parameter_space, n_jobs=-1, cv=5) #cv=5 means 5 fold cv

In [64]:
clf.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=10), n_jobs=-1,
             param_grid={'max_depth': [10, 15, 8, 12],
                         'min_samples_leaf': [1, 3, 4, 5, 6, 7]})

In [65]:
print('best parameters found:\n',clf.best_params_) 

best parameters found:
 {'max_depth': 10, 'min_samples_leaf': 5}


In [66]:
clf.best_score_  #cv accuracy list avg score - cv score

0.874134962406891

In [67]:
y_pred_clf=clf.predict(x_test)

In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(y_test,y_pred_clf)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(y_test,y_pred_clf))
 
acc=accuracy_score(y_test, y_pred_clf)
print("Accuracy of the model: ",acc)

[[412  40   0]
 [ 41 306  39]
 [  0  35 285]]
Classification report: 
              precision    recall  f1-score   support

    Consider       0.91      0.91      0.91       452
May Consider       0.80      0.79      0.80       386
Not Consider       0.88      0.89      0.89       320

    accuracy                           0.87      1158
   macro avg       0.86      0.86      0.86      1158
weighted avg       0.87      0.87      0.87      1158

Accuracy of the model:  0.8661485319516408


In [69]:
from sklearn.ensemble import RandomForestClassifier
 
model_RF1= RandomForestClassifier(random_state=10, bootstrap=True) #fixed parameters should be passsed here
 
#parameters for trial and error should be passed here
parameter_space = {
    'n_estimators':[100,300,500],       #np.arange(100, 1001,50),
    'max_depth':[10,15,8, 12],
    'min_samples_leaf':[1,3,4,5,6,7]
    }
from sklearn.model_selection import GridSearchCV #RandomizedSearchCV
clf1 = GridSearchCV(model_RF1, parameter_space, n_jobs=-1, cv=5) #cv=5 means 5 fold cv

In [70]:
clf1.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=10), n_jobs=-1,
             param_grid={'max_depth': [10, 15, 8, 12],
                         'min_samples_leaf': [1, 3, 4, 5, 6, 7],
                         'n_estimators': [100, 300, 500]})

In [71]:
print('best parameters found:\n',clf1.best_params_) 

best parameters found:
 {'max_depth': 15, 'min_samples_leaf': 1, 'n_estimators': 300}


In [72]:
clf1.best_score_  #cv accuracy list avg score - cv score

0.8996125358515009

In [73]:
y_pred_clf1=clf1.predict(x_test)

In [74]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(y_test,y_pred_clf1)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(y_test,y_pred_clf1))
 
acc=accuracy_score(y_test, y_pred_clf1)
print("Accuracy of the model: ",acc)

[[415  37   0]
 [ 44 313  29]
 [  0  26 294]]
Classification report: 
              precision    recall  f1-score   support

    Consider       0.90      0.92      0.91       452
May Consider       0.83      0.81      0.82       386
Not Consider       0.91      0.92      0.91       320

    accuracy                           0.88      1158
   macro avg       0.88      0.88      0.88      1158
weighted avg       0.88      0.88      0.88      1158

Accuracy of the model:  0.8825561312607945


In [88]:
from sklearn.ensemble import ExtraTreesClassifier
 
model_EXT= ExtraTreesClassifier(random_state=10, bootstrap=True) #fixed parameters should be passsed here
 
#parameters for trial and error should be passed here
parameter_space = {
    'n_estimators':[100,300,350,400,500],       #np.arange(100, 1001,50),
    'max_depth':[10,15,8, 12],
    'min_samples_leaf':[1,3,4,5,6,7]
    }
from sklearn.model_selection import GridSearchCV #RandomizedSearchCV
clf2 = GridSearchCV(model_EXT, parameter_space, n_jobs=-1, cv=5) #cv=5 means 5 fold cv

In [89]:
clf2.fit(x_train,y_train)

GridSearchCV(cv=5,
             estimator=ExtraTreesClassifier(bootstrap=True, random_state=10),
             n_jobs=-1,
             param_grid={'max_depth': [10, 15, 8, 12],
                         'min_samples_leaf': [1, 3, 4, 5, 6, 7],
                         'n_estimators': [100, 300, 350, 400, 500]})

In [90]:
print('best parameters found:\n',clf2.best_params_)

best parameters found:
 {'max_depth': 12, 'min_samples_leaf': 3, 'n_estimators': 500}


In [91]:
clf2.best_score_  #cv accuracy list avg score - cv score

0.8987497699213189

In [92]:
y_pred_clf2=clf2.predict(x_test)

In [93]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(y_test,y_pred_clf2)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(y_test,y_pred_clf2))
 
acc=accuracy_score(y_test, y_pred_clf2)
print("Accuracy of the model: ",acc)

[[432  20   0]
 [ 57 298  31]
 [  0  29 291]]
Classification report: 
              precision    recall  f1-score   support

    Consider       0.88      0.96      0.92       452
May Consider       0.86      0.77      0.81       386
Not Consider       0.90      0.91      0.91       320

    accuracy                           0.88      1158
   macro avg       0.88      0.88      0.88      1158
weighted avg       0.88      0.88      0.88      1158

Accuracy of the model:  0.8816925734024179


In [75]:
from sklearn.linear_model import LogisticRegression
#create a model object
classifier = LogisticRegression()
#train the model object
classifier.fit(x_train, y_train)

#print intercepts and coefficients
print(classifier.intercept_)
print(classifier.coef_)

[ 0.22261242  4.61598695 -4.83859937]
[[-8.36327504e-02 -1.37644872e-02  1.37644872e-02  2.13226018e-02
  -8.59014102e-02  3.24887552e+00 -6.99986202e-02 -1.21568781e+01
  -3.62789821e-03 -2.63835946e+00  4.48185167e-02 -3.73465318e-02
   3.43794499e+00 -6.31118736e-01 -5.63137652e-02 -5.16747235e-03
   8.81221945e-03 -3.19650247e-02 -5.95244906e-02  1.82651382e+00
  -8.66007191e-02 -2.32991595e-02  1.53334980e-02]
 [-4.57753430e-03  4.83543148e-03 -4.83543148e-03 -8.28770764e-06
   4.06444796e-02  1.92541606e-02 -1.39395054e-02  7.91985872e-02
   1.66015078e-02  5.48254196e-03 -2.03660734e-02  4.12288141e-03
   5.20826963e-02  3.29185764e-02  1.09608408e-02 -1.68630317e-02
  -7.21447661e-03  1.26799919e-02  2.21382305e-02 -3.34419906e-02
   4.43371759e-02  4.17996119e-03 -3.05830446e-02]
 [ 8.82102847e-02  8.92905574e-03 -8.92905574e-03 -2.13143141e-02
   4.52569306e-02 -3.26812968e+00  8.39381256e-02  1.20776795e+01
  -1.29736096e-02  2.63287692e+00 -2.44524433e-02  3.32236503e-02
  

In [76]:
Y_pred_logistic = classifier.predict(x_test)
print(Y_pred_logistic)

['May Consider' 'Not Consider' 'Not Consider' ... 'Consider' 'Consider'
 'May Consider']


In [77]:
Y_pred_prob = classifier.predict_proba(x_test)
print(Y_pred_prob)
#This is a probability matrix which tells us the probability of a variable belonging to class 0 and class 1.
#Default threshold is 0.5
#So if we see class 0 beats the threshold value.

[[1.87947046e-01 8.12050292e-01 2.66242558e-06]
 [6.20574456e-08 2.05237931e-01 7.94762007e-01]
 [2.59863133e-16 2.57583850e-05 9.99974242e-01]
 ...
 [9.89563074e-01 1.04369261e-02 1.08925347e-10]
 [9.98664164e-01 1.33583577e-03 2.16602731e-12]
 [4.38196150e-03 9.95479322e-01 1.38716195e-04]]


In [78]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(y_test,Y_pred_logistic)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(y_test,Y_pred_logistic))
 
acc=accuracy_score(y_test, Y_pred_logistic)
print("Accuracy of the model: ",acc)

[[446   6   0]
 [  1 381   4]
 [  0   3 317]]
Classification report: 
              precision    recall  f1-score   support

    Consider       1.00      0.99      0.99       452
May Consider       0.98      0.99      0.98       386
Not Consider       0.99      0.99      0.99       320

    accuracy                           0.99      1158
   macro avg       0.99      0.99      0.99      1158
weighted avg       0.99      0.99      0.99      1158

Accuracy of the model:  0.9879101899827288


In [79]:
np.set_printoptions(suppress = True)

In [80]:
Y_pred_prob = classifier.predict_proba(x_test)
print(Y_pred_prob)

[[0.18794705 0.81205029 0.00000266]
 [0.00000006 0.20523793 0.79476201]
 [0.         0.00002576 0.99997424]
 ...
 [0.98956307 0.01043693 0.        ]
 [0.99866416 0.00133584 0.        ]
 [0.00438196 0.99547932 0.00013872]]


In [81]:
classifier.score(x_train, y_train)

0.9950345423143351

In [82]:
# Test file predictions using logistic Regression

In [83]:
Y_pred_test_file = classifier.predict(test_df_scaled)
print(Y_pred_test_file)

['Consider' 'Not Consider' 'Not Consider' ... 'Not Consider'
 'Not Consider' 'Not Consider']


In [84]:
len(Y_pred_test_file)

1187

In [85]:
test_df.shape

(1187, 23)

In [86]:
Predictions_df=pd.DataFrame(test_df.index,columns=['Interview Id'])
Predictions_df['Candidate Interview Status Predictions']=Y_pred_test_file
Predictions_df

Interview Id Candidate Interview Status Predictions
0     702127796635                               Consider
1     613490569071                           Not Consider
2     759998772623                           Not Consider
3     391760082113                           Not Consider
4     941599210196                           Not Consider
...            ...                                    ...
1182  256033687434                           Not Consider
1183  627337316047                           Not Consider
1184   75547031851                           Not Consider
1185  173914777164                           Not Consider
1186  480519602140                           Not Consider

[1187 rows x 2 columns]

In [87]:
#Predictions_df.to_csv('Candidate Interview Status Predictions.csv',index=False,header=True)